language: julia

os:
  - osx
  - linux

julia:
  - release
  - nightly
  
notifications:
  email: false
 
before_install:
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("OptimTools"); Pkg.test("OptimTools"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("OptimTools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'